### ISSUE TITLE
How to generate Bearer for API's

### ISSUE THREAD

**Issue by anishmenon** [raystack/frontier#346]
i've deployed the frontier on digitalocean kubernetes with spiceDB i've followed the raystack official helm charts and modify its values to setup.

But how can i setup server side secret key for JWT via helm values. I didnt see anywhere in docs.

i've generated key using `frontier server keygen` locally. How can i do with configMaps or any other method. Also method to generate JWT for API communication.

eg : v1beta1/admin/users
now i;m getting below error. as i'm not passing bearer token.

{"code":16, "message":"not authenticated", "details":[]}

Please guide

**Comment by kushsharma** [comment]
@anishmenon JWT requires first setting up RSA keys for frontier, what you get using `frontier server keygen` are the private RSA keys. We must pass these keys using a `config map` to the frontier when it boots up. The reason it is not part of the chart is various people use various ways to pass it as a secure credential. 

One easy way is to create a helm file `templates/configmap-files.yaml` within `frontier` charts directory and use
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-files"
  namespace: "{{ include "app.namespace" . }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
{{- if .Values.configPath }}
{{ (tpl (.Files.Glob (printf "%s" .Values.configPath) ).AsConfig . ) | indent 2 }}
{{- end }}
```

Create one more directory in frontier with the name `files` and add the generated key in a file called `rsa` and put it in this directory as `./files/rsa`

In `values.yaml` add a line at the top, this will ensure our config map reads all the files from `files` directory and adds them as a key-value pair in the config map of kube.
```yaml
configPath: "files/**"
```
So far we have put our RSA key in a config map but for frontier to find these keys we also need to mount it. Modify the frontier `values.yaml` as follows
```yaml
container:
    command: ["frontier", "server", "start"]
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8081
      protocol: TCP
    volumeMounts:
    - name: configs
      mountPath: /etc/config
  volumes:
  - name: configs
    configMap:
      name: frontier-files
  config:
    FRONTIER_APP_AUTHENTICATION_TOKEN_RSA_PATH: /etc/config/rsa
```
Notice the newly added `volumes` and additional env config.

But before you do all this, I would advise you to setup everything in your local machine using docker and test how it works. Let me know if you need help in setting up locally.
