### ISSUE TITLE
Introduce resource_type in resource config

### ISSUE THREAD

**Issue by krtkvrm** [raystack/frontier#75]
resource.yml will have another nesting inside a resource field, called as resource_type. it will be used to denote that a resource aka backend can have multiple resource_types which will be created a definition or namespace in spicedb as well as used in shield.

the new namespace will be of format `{old_namespace}_{resource_type}`
```
resources:
  - name: "guardian"
    resource_name:
      - name: "appeal"
        actions:
          read:
            - owner
            - organization.users
          delete:
            - owner
      - name: "appeal"
          actions:
            read:
              - owner
              - organization.users
            delete:
              - owner
  - name: "siren"
      resource_name:
        - name: "alert"
          actions:
            read:
              - owner
              - organization.users
            delete:
              - owner
            access_xyz:
              - organization.admin
  - name: "entropy"
      resource_name:
        - name: "firehose"
          actions:
            read:
              - owner
              - organization.users
            delete:
              - owner
```
